Document: pobkup
Title: Debian pobkup Manual
Author: <insert document author here>
Abstract: This manual describes what pobkup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pobkup/pobkup.sgml.gz

Format: postscript
Files: /usr/share/doc/pobkup/pobkup.ps.gz

Format: text
Files: /usr/share/doc/pobkup/pobkup.text.gz

Format: HTML
Index: /usr/share/doc/pobkup/html/index.html
Files: /usr/share/doc/pobkup/html/*.html
